    LIST P=18F4520
#INCLUDE <P18F4520.INC>
    CONFIG OSC=HS
    CONFIG LVP=OFF
    CONFIG MCLRE = OFF
;    CONFIG	FCMEN = OFF ;disable fail safe clock monitor
;    CONFIG	IESO = OFF  ;disable internal/external switch over
;    CONFIG	PWRT = ON   ;power up timer on
;    CONFIG	BOREN = OFF ;disable brown out reset	
;    CONFIG	WDT = OFF   ;turn off WDT
;    CONFIG	MCLRE = OFF ;tie MCLR to Vdd, free up
;    CONFIG	PBADEN = OFF;port B<4:0> dare configured as digital I/O on
;    CONFIG	LVP = OFF   ;disable low voltage ICSP
;    CONFIG	XINST = OFF ;Extended instruction set disabled
    CBLOCK 0X00
CHUC
DONVI
DEM1
DEM2
DEMLAN1
ENABLE
ENABLE1
START
W_TEMP
STATUS_TEMP
    ENDC

    ORG 0X00
    GOTO MAIN
    ORG 0X08
    GOTO NGAT
MAIN
    CLRF TRISD
    CLRF TRISC
    CLRF TRISA
    MOVLW 0X07
    MOVWF TRISB
    MOVLW 0X0F
    MOVWF ADCON1
    MOVLW 0X07
    MOVWF CMCON
    BSF INTCON,7
    BSF INTCON,4
    BCF INTCON2,7
    BCF INTCON2,6
    BSF INTCON3,3
    BSF INTCON3,4
    BSF T0CON,7
    BCF T0CON,6
    BCF T0CON,5
    BCF T0CON,3
    BSF T0CON,2
    BCF T0CON,1
    BCF T0CON,0
    CLRF TRISD
    SETF START
    SETF ENABLE
    CLRF ENABLE1
    MOVLW D'50'
    MOVWF DEMLAN1
    
LOOP
    MOVLW 0XFF
    CPFSEQ START
    GOTO LOOP

LOOP1
    MOVLW 0X00
    CPFSEQ ENABLE1	;ENABLE1 = 0XFF THI VAO CT CON LOOP2 DE HEIN THI DEN
    GOTO LOOP2
    MOVLW D'0'
    CPFSEQ DEMLAN1
    GOTO DEMTHU1
    BCF PORTD,3

LOOP2
    CALL HIENTHI
    CALL SANGDEN
    GOTO LOOP1

DEMTHU1
    DECF DEMLAN1,1
    GOTO BATDEN

BATDEN
    BSF PORTD,3
    GOTO LOOP2

HIENTHI
    MOVLW 0XFF
    CPFSEQ START
    GOTO START1
    MOVF DONVI,0
    CALL MANGMA
    MOVWF DEM1
    MOVF CHUC,0
    CALL MANGMA
    MOVWF DEM2
    MOVLW 0X01
    MOVWF PORTA
    MOVF DEM1,0
    MOVWF PORTC
    CALL DELAY
    MOVLW 0X02
    MOVWF PORTA
    MOVF DEM2,0
    MOVWF PORTC
    CALL DELAY
    RETURN

MANGMA
    ADDWF PCL,1
    DT 0xC0, 0xF9, 0xA4, 0xB0, 0x99, 0x92, 0x82, 0xF8, 0x80, 0x90

START1
    CLRF CHUC
    CLRF DONVI
    CLRF PORTA
    BCF PORTD,0
    BCF PORTD,1
    BCF PORTD,2
    RETURN

DELAY
    MOVLW 0XF9
    MOVWF TMR0H
    MOVLW 0XE5
    MOVWF TMR0L
    BTFSS INTCON,2
    GOTO $-2
    BCF INTCON,2
    RETURN

NGAT
    BTFSC INTCON,1
    GOTO NGAT_RB0
    BTFSC INTCON3,0
    GOTO NGAT_RB1
    BTFSC INTCON3,1
    GOTO NGAT_RB2
    RETFIE

NGAT_RB1  ; NGAT INT1
    COMF START
    MOVLW 0XFF
    CPFSEQ START
    GOTO RB1_OFF
    BCF INTCON3,0
    RETFIE

RB1_OFF                
    BCF PORTD,3
    SETF ENABLE
    CLRF ENABLE1
    BCF INTCON3,0
    RETFIE

NGAT_RB2 ; NGAT INT2
    COMF ENABLE
    COMF ENABLE1
    BSF PORTD,3
    BCF INTCON3,1
    RETFIE

NGAT_RB0	;NGAT INT0
    MOVWF W_TEMP
    MOVFF STATUS,STATUS_TEMP
    MOVLW 0XFF
    CPFSEQ START                     
    GOTO THOAT1                       
    CPFSEQ ENABLE
    GOTO THOAT
    MOVLW D'18'
    CPFSEQ CHUC
    GOTO CAP_NHAT
    CPFSEQ DONVI
    GOTO CAP_NHAT
    GOTO THOAT

CAP_NHAT
    INCF DONVI
    INCF DONVI
    MOVF DONVI,0
    XORLW D'20'
    BTFSS STATUS,Z
    GOTO THOAT
    CLRF DONVI
    INCF CHUC
    INCF CHUC
    MOVF CHUC,0
    XORLW D'20'
    BTFSS STATUS,Z
    GOTO THOAT

THOAT
    CALL SANGDEN
    BSF PORTD,3
    MOVLW D'50'
    MOVWF DEMLAN1

THOAT1
    MOVF W_TEMP,0
    MOVFF STATUS_TEMP,STATUS
    BCF INTCON,1
    RETFIE

SANGDEN
    BCF STATUS,C
    MOVLW D'2'
    SUBWF CHUC,0
    BTFSS STATUS,C
    GOTO SANG0
    BCF STATUS,C
    MOVLW D'4'
    SUBWF CHUC,0
    BTFSS STATUS,C
    GOTO SANG1
    BCF STATUS,C
    MOVLW D'6'
    SUBWF CHUC,0
    BTFSS STATUS,C
    GOTO SANG2
    BCF STATUS,C
    MOVLW D'8'
    SUBWF CHUC,0
    BTFSS STATUS,C
    GOTO SANG3
    RETURN

SANG0
    BCF PORTD,0
    BCF PORTD,1
    BCF PORTD,2
    RETURN

SANG1
    BSF PORTD,0
    BCF PORTD,1
    BCF PORTD,2
    RETURN

SANG2
    BCF PORTD,0
    BSF PORTD,1
    BCF PORTD,2
    RETURN

SANG3
    BCF PORTD,0
    BCF PORTD,1
    BSF PORTD,2
    RETURN

    END